name: MindPulse
options:
  bundleIdPrefix: com.mindpulse
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1

targets:
  MindPulse:
    type: application
    platform: iOS
    sources:
      - MindPulse
    settings:
      base:
        INFOPLIST_FILE: MindPulse/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.mindpulse.app
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        TARGETED_DEVICE_FAMILY: 1
        SWIFT_EMIT_LOC_STRINGS: YES
    info:
      path: MindPulse/Info.plist
      properties:
        CFBundleDisplayName: MindPulse
        CFBundleName: MindPulse
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        ITSAppUsesNonExemptEncryption: false
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
